[project]
name = "pydantic-project"
version = "0.1.0"
description = "Project with Pydantic and FastAPI, from a Udemy course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
